services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    ControleOnline\:
        resource: '../../src/*'
        exclude: '../src/{DependencyInjection,Entity,Resource,Migrations,Library,Tests,Kernel.php}'
    ControleOnline\Repository\:
        resource: '../../src/Repository'
        tags: ['doctrine.repository_service']
    ControleOnline\Controller\:
        resource: '../../src/Controller'
        tags: ['controller.service_arguments']
    # Os serviços abaixo agora dependem do autowiring para a injeção de dependências
    ControleOnline\Service\DatabaseSwitchService: ~
    ControleOnline\EventListener\DatabaseSwitchListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 512 }
    ControleOnline\Command\:
        resource: '../../src/Command'
        tags: ['console.command']
    ControleOnline\Filter\:
        resource: '../../src/Filter'            